name: Release mstodo

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v.*"
      - uses: wangyoucao577/go-release-action@v1.18
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: "-s -w -X 'github.com/dalyisaac/mstodo/build.Version=v1.0.0'"
